sudo: required
services:
  - docker

before_install: 
  - docker build -t yarob50/node-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true yarob50/node-docker npm run test


  deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "node-docker"
    env: "NodeDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-925342842908"
    bucket_path: "node-docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secret: "$AWS_SECRET_KEY"

